-- MySQL Script generated by MySQL Workbench
-- Thu 19 Apr 2018 01:29:48 AM PDT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema cmpe275
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema cmpe275
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cmpe275` DEFAULT CHARACTER SET latin1 ;
USE `cmpe275` ;

-- -----------------------------------------------------
-- Table `cmpe275`.`chunks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cmpe275`.`chunks` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `file_id` INT(11) NOT NULL,
  `chunk_id` INT(11) NOT NULL,
  `location_at` VARCHAR(200) NOT NULL,
  `chunk_size` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `file_id` (`file_id` ASC, `chunk_id` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `cmpe275`.`files`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cmpe275`.`files` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `file_ext` VARCHAR(20) NULL DEFAULT NULL,
  `total_chunks` INT(11) NULL DEFAULT NULL,
  `chunks_available` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
