// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: election.proto

package pipe.election;

public final class Election {
  private Election() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface LeaderStatusOrBuilder extends
      // @@protoc_insertion_point(interface_extends:LeaderStatus)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required .LeaderStatus.LeaderQuery action = 1;</code>
     */
    boolean hasAction();
    /**
     * <code>required .LeaderStatus.LeaderQuery action = 1;</code>
     */
    LeaderStatus.LeaderQuery getAction();

    /**
     * <code>optional .LeaderStatus.LeaderState state = 2;</code>
     */
    boolean hasState();
    /**
     * <code>optional .LeaderStatus.LeaderState state = 2;</code>
     */
    LeaderStatus.LeaderState getState();

    /**
     * <code>optional string leader_host = 3;</code>
     */
    boolean hasLeaderHost();
    /**
     * <code>optional string leader_host = 3;</code>
     */
    String getLeaderHost();
    /**
     * <code>optional string leader_host = 3;</code>
     */
    com.google.protobuf.ByteString
        getLeaderHostBytes();

    /**
     * <code>optional int32 leader_id = 4;</code>
     */
    boolean hasLeaderId();
    /**
     * <code>optional int32 leader_id = 4;</code>
     */
    int getLeaderId();
  }
  /**
   * Protobuf type {@code LeaderStatus}
   *
   * <pre>
   * enquire about the state of the leader/election
   * </pre>
   */
  public static final class LeaderStatus extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:LeaderStatus)
      LeaderStatusOrBuilder {
    // Use LeaderStatus.newBuilder() to construct.
    private LeaderStatus(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private LeaderStatus(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final LeaderStatus defaultInstance;
    public static LeaderStatus getDefaultInstance() {
      return defaultInstance;
    }

    public LeaderStatus getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private LeaderStatus(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              LeaderQuery value = LeaderQuery.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                action_ = value;
              }
              break;
            }
            case 16: {
              int rawValue = input.readEnum();
              LeaderState value = LeaderState.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(2, rawValue);
              } else {
                bitField0_ |= 0x00000002;
                state_ = value;
              }
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              leaderHost_ = bs;
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              leaderId_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Election.internal_static_LeaderStatus_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Election.internal_static_LeaderStatus_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              LeaderStatus.class, Builder.class);
    }

    public static com.google.protobuf.Parser<LeaderStatus> PARSER =
        new com.google.protobuf.AbstractParser<LeaderStatus>() {
      public LeaderStatus parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new LeaderStatus(input, extensionRegistry);
      }
    };

    @Override
    public com.google.protobuf.Parser<LeaderStatus> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code LeaderStatus.LeaderState}
     */
    public enum LeaderState
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>LEADERUNKNOWN = 1;</code>
       */
      LEADERUNKNOWN(0, 1),
      /**
       * <code>LEADERALIVE = 2;</code>
       */
      LEADERALIVE(1, 2),
      /**
       * <code>LEADERDEAD = 3;</code>
       */
      LEADERDEAD(2, 3),
      ;

      /**
       * <code>LEADERUNKNOWN = 1;</code>
       */
      public static final int LEADERUNKNOWN_VALUE = 1;
      /**
       * <code>LEADERALIVE = 2;</code>
       */
      public static final int LEADERALIVE_VALUE = 2;
      /**
       * <code>LEADERDEAD = 3;</code>
       */
      public static final int LEADERDEAD_VALUE = 3;


      public final int getNumber() { return value; }

      public static LeaderState valueOf(int value) {
        switch (value) {
          case 1: return LEADERUNKNOWN;
          case 2: return LEADERALIVE;
          case 3: return LEADERDEAD;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<LeaderState>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<LeaderState>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<LeaderState>() {
              public LeaderState findValueByNumber(int number) {
                return LeaderState.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return LeaderStatus.getDescriptor().getEnumTypes().get(0);
      }

      private static final LeaderState[] VALUES = values();

      public static LeaderState valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private LeaderState(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:LeaderStatus.LeaderState)
    }

    /**
     * Protobuf enum {@code LeaderStatus.LeaderQuery}
     */
    public enum LeaderQuery
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>WHOISTHELEADER = 1;</code>
       */
      WHOISTHELEADER(0, 1),
      /**
       * <code>THELEADERIS = 2;</code>
       */
      THELEADERIS(1, 2),
      ;

      /**
       * <code>WHOISTHELEADER = 1;</code>
       */
      public static final int WHOISTHELEADER_VALUE = 1;
      /**
       * <code>THELEADERIS = 2;</code>
       */
      public static final int THELEADERIS_VALUE = 2;


      public final int getNumber() { return value; }

      public static LeaderQuery valueOf(int value) {
        switch (value) {
          case 1: return WHOISTHELEADER;
          case 2: return THELEADERIS;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<LeaderQuery>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<LeaderQuery>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<LeaderQuery>() {
              public LeaderQuery findValueByNumber(int number) {
                return LeaderQuery.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return LeaderStatus.getDescriptor().getEnumTypes().get(1);
      }

      private static final LeaderQuery[] VALUES = values();

      public static LeaderQuery valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private LeaderQuery(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:LeaderStatus.LeaderQuery)
    }

    private int bitField0_;
    public static final int ACTION_FIELD_NUMBER = 1;
    private LeaderQuery action_;
    /**
     * <code>required .LeaderStatus.LeaderQuery action = 1;</code>
     */
    public boolean hasAction() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .LeaderStatus.LeaderQuery action = 1;</code>
     */
    public LeaderQuery getAction() {
      return action_;
    }

    public static final int STATE_FIELD_NUMBER = 2;
    private LeaderState state_;
    /**
     * <code>optional .LeaderStatus.LeaderState state = 2;</code>
     */
    public boolean hasState() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional .LeaderStatus.LeaderState state = 2;</code>
     */
    public LeaderState getState() {
      return state_;
    }

    public static final int LEADER_HOST_FIELD_NUMBER = 3;
    private Object leaderHost_;
    /**
     * <code>optional string leader_host = 3;</code>
     */
    public boolean hasLeaderHost() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string leader_host = 3;</code>
     */
    public String getLeaderHost() {
      Object ref = leaderHost_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          leaderHost_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string leader_host = 3;</code>
     */
    public com.google.protobuf.ByteString
        getLeaderHostBytes() {
      Object ref = leaderHost_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        leaderHost_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LEADER_ID_FIELD_NUMBER = 4;
    private int leaderId_;
    /**
     * <code>optional int32 leader_id = 4;</code>
     */
    public boolean hasLeaderId() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional int32 leader_id = 4;</code>
     */
    public int getLeaderId() {
      return leaderId_;
    }

    private void initFields() {
      action_ = LeaderQuery.WHOISTHELEADER;
      state_ = LeaderState.LEADERUNKNOWN;
      leaderHost_ = "";
      leaderId_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasAction()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, action_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeEnum(2, state_.getNumber());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getLeaderHostBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, leaderId_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, action_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, state_.getNumber());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getLeaderHostBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, leaderId_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static LeaderStatus parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static LeaderStatus parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static LeaderStatus parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static LeaderStatus parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static LeaderStatus parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static LeaderStatus parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static LeaderStatus parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static LeaderStatus parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static LeaderStatus parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static LeaderStatus parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(LeaderStatus prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code LeaderStatus}
     *
     * <pre>
     * enquire about the state of the leader/election
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:LeaderStatus)
        LeaderStatusOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Election.internal_static_LeaderStatus_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Election.internal_static_LeaderStatus_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                LeaderStatus.class, Builder.class);
      }

      // Construct using pipe.election.Election.LeaderStatus.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        action_ = LeaderQuery.WHOISTHELEADER;
        bitField0_ = (bitField0_ & ~0x00000001);
        state_ = LeaderState.LEADERUNKNOWN;
        bitField0_ = (bitField0_ & ~0x00000002);
        leaderHost_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        leaderId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Election.internal_static_LeaderStatus_descriptor;
      }

      public LeaderStatus getDefaultInstanceForType() {
        return LeaderStatus.getDefaultInstance();
      }

      public LeaderStatus build() {
        LeaderStatus result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public LeaderStatus buildPartial() {
        LeaderStatus result = new LeaderStatus(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.action_ = action_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.state_ = state_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.leaderHost_ = leaderHost_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.leaderId_ = leaderId_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof LeaderStatus) {
          return mergeFrom((LeaderStatus)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(LeaderStatus other) {
        if (other == LeaderStatus.getDefaultInstance()) return this;
        if (other.hasAction()) {
          setAction(other.getAction());
        }
        if (other.hasState()) {
          setState(other.getState());
        }
        if (other.hasLeaderHost()) {
          bitField0_ |= 0x00000004;
          leaderHost_ = other.leaderHost_;
          onChanged();
        }
        if (other.hasLeaderId()) {
          setLeaderId(other.getLeaderId());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasAction()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        LeaderStatus parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (LeaderStatus) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private LeaderQuery action_ = LeaderQuery.WHOISTHELEADER;
      /**
       * <code>required .LeaderStatus.LeaderQuery action = 1;</code>
       */
      public boolean hasAction() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .LeaderStatus.LeaderQuery action = 1;</code>
       */
      public LeaderQuery getAction() {
        return action_;
      }
      /**
       * <code>required .LeaderStatus.LeaderQuery action = 1;</code>
       */
      public Builder setAction(LeaderQuery value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        action_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .LeaderStatus.LeaderQuery action = 1;</code>
       */
      public Builder clearAction() {
        bitField0_ = (bitField0_ & ~0x00000001);
        action_ = LeaderQuery.WHOISTHELEADER;
        onChanged();
        return this;
      }

      private LeaderState state_ = LeaderState.LEADERUNKNOWN;
      /**
       * <code>optional .LeaderStatus.LeaderState state = 2;</code>
       */
      public boolean hasState() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional .LeaderStatus.LeaderState state = 2;</code>
       */
      public LeaderState getState() {
        return state_;
      }
      /**
       * <code>optional .LeaderStatus.LeaderState state = 2;</code>
       */
      public Builder setState(LeaderState value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        state_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .LeaderStatus.LeaderState state = 2;</code>
       */
      public Builder clearState() {
        bitField0_ = (bitField0_ & ~0x00000002);
        state_ = LeaderState.LEADERUNKNOWN;
        onChanged();
        return this;
      }

      private Object leaderHost_ = "";
      /**
       * <code>optional string leader_host = 3;</code>
       */
      public boolean hasLeaderHost() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string leader_host = 3;</code>
       */
      public String getLeaderHost() {
        Object ref = leaderHost_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            leaderHost_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string leader_host = 3;</code>
       */
      public com.google.protobuf.ByteString
          getLeaderHostBytes() {
        Object ref = leaderHost_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          leaderHost_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string leader_host = 3;</code>
       */
      public Builder setLeaderHost(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        leaderHost_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string leader_host = 3;</code>
       */
      public Builder clearLeaderHost() {
        bitField0_ = (bitField0_ & ~0x00000004);
        leaderHost_ = getDefaultInstance().getLeaderHost();
        onChanged();
        return this;
      }
      /**
       * <code>optional string leader_host = 3;</code>
       */
      public Builder setLeaderHostBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        leaderHost_ = value;
        onChanged();
        return this;
      }

      private int leaderId_ ;
      /**
       * <code>optional int32 leader_id = 4;</code>
       */
      public boolean hasLeaderId() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional int32 leader_id = 4;</code>
       */
      public int getLeaderId() {
        return leaderId_;
      }
      /**
       * <code>optional int32 leader_id = 4;</code>
       */
      public Builder setLeaderId(int value) {
        bitField0_ |= 0x00000008;
        leaderId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 leader_id = 4;</code>
       */
      public Builder clearLeaderId() {
        bitField0_ = (bitField0_ & ~0x00000008);
        leaderId_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:LeaderStatus)
    }

    static {
      defaultInstance = new LeaderStatus(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:LeaderStatus)
  }

  public interface LeaderElectionOrBuilder extends
      // @@protoc_insertion_point(interface_extends:LeaderElection)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 term = 1;</code>
     */
    boolean hasTerm();
    /**
     * <code>required int32 term = 1;</code>
     */
    int getTerm();

    /**
     * <code>required int32 candidateId = 2;</code>
     */
    boolean hasCandidateId();
    /**
     * <code>required int32 candidateId = 2;</code>
     */
    int getCandidateId();

    /**
     * <code>required int32 lastLogIndex = 3;</code>
     */
    boolean hasLastLogIndex();
    /**
     * <code>required int32 lastLogIndex = 3;</code>
     */
    int getLastLogIndex();

    /**
     * <code>required int32 lastLogTerm = 4;</code>
     */
    boolean hasLastLogTerm();
    /**
     * <code>required int32 lastLogTerm = 4;</code>
     */
    int getLastLogTerm();
  }
  /**
   * Protobuf type {@code LeaderElection}
   */
  public static final class LeaderElection extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:LeaderElection)
      LeaderElectionOrBuilder {
    // Use LeaderElection.newBuilder() to construct.
    private LeaderElection(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private LeaderElection(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final LeaderElection defaultInstance;
    public static LeaderElection getDefaultInstance() {
      return defaultInstance;
    }

    public LeaderElection getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private LeaderElection(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              term_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              candidateId_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              lastLogIndex_ = input.readInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              lastLogTerm_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Election.internal_static_LeaderElection_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Election.internal_static_LeaderElection_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              LeaderElection.class, Builder.class);
    }

    public static com.google.protobuf.Parser<LeaderElection> PARSER =
        new com.google.protobuf.AbstractParser<LeaderElection>() {
      public LeaderElection parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new LeaderElection(input, extensionRegistry);
      }
    };

    @Override
    public com.google.protobuf.Parser<LeaderElection> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int TERM_FIELD_NUMBER = 1;
    private int term_;
    /**
     * <code>required int32 term = 1;</code>
     */
    public boolean hasTerm() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 term = 1;</code>
     */
    public int getTerm() {
      return term_;
    }

    public static final int CANDIDATEID_FIELD_NUMBER = 2;
    private int candidateId_;
    /**
     * <code>required int32 candidateId = 2;</code>
     */
    public boolean hasCandidateId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 candidateId = 2;</code>
     */
    public int getCandidateId() {
      return candidateId_;
    }

    public static final int LASTLOGINDEX_FIELD_NUMBER = 3;
    private int lastLogIndex_;
    /**
     * <code>required int32 lastLogIndex = 3;</code>
     */
    public boolean hasLastLogIndex() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int32 lastLogIndex = 3;</code>
     */
    public int getLastLogIndex() {
      return lastLogIndex_;
    }

    public static final int LASTLOGTERM_FIELD_NUMBER = 4;
    private int lastLogTerm_;
    /**
     * <code>required int32 lastLogTerm = 4;</code>
     */
    public boolean hasLastLogTerm() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required int32 lastLogTerm = 4;</code>
     */
    public int getLastLogTerm() {
      return lastLogTerm_;
    }

    private void initFields() {
      term_ = 0;
      candidateId_ = 0;
      lastLogIndex_ = 0;
      lastLogTerm_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasTerm()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasCandidateId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLastLogIndex()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLastLogTerm()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, term_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, candidateId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, lastLogIndex_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, lastLogTerm_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, term_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, candidateId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, lastLogIndex_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, lastLogTerm_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static LeaderElection parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static LeaderElection parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static LeaderElection parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static LeaderElection parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static LeaderElection parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static LeaderElection parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static LeaderElection parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static LeaderElection parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static LeaderElection parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static LeaderElection parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(LeaderElection prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code LeaderElection}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:LeaderElection)
        LeaderElectionOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Election.internal_static_LeaderElection_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Election.internal_static_LeaderElection_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                LeaderElection.class, Builder.class);
      }

      // Construct using pipe.election.Election.LeaderElection.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        term_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        candidateId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        lastLogIndex_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        lastLogTerm_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Election.internal_static_LeaderElection_descriptor;
      }

      public LeaderElection getDefaultInstanceForType() {
        return LeaderElection.getDefaultInstance();
      }

      public LeaderElection build() {
        LeaderElection result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public LeaderElection buildPartial() {
        LeaderElection result = new LeaderElection(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.term_ = term_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.candidateId_ = candidateId_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.lastLogIndex_ = lastLogIndex_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.lastLogTerm_ = lastLogTerm_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof LeaderElection) {
          return mergeFrom((LeaderElection)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(LeaderElection other) {
        if (other == LeaderElection.getDefaultInstance()) return this;
        if (other.hasTerm()) {
          setTerm(other.getTerm());
        }
        if (other.hasCandidateId()) {
          setCandidateId(other.getCandidateId());
        }
        if (other.hasLastLogIndex()) {
          setLastLogIndex(other.getLastLogIndex());
        }
        if (other.hasLastLogTerm()) {
          setLastLogTerm(other.getLastLogTerm());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasTerm()) {
          
          return false;
        }
        if (!hasCandidateId()) {
          
          return false;
        }
        if (!hasLastLogIndex()) {
          
          return false;
        }
        if (!hasLastLogTerm()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        LeaderElection parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (LeaderElection) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int term_ ;
      /**
       * <code>required int32 term = 1;</code>
       */
      public boolean hasTerm() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 term = 1;</code>
       */
      public int getTerm() {
        return term_;
      }
      /**
       * <code>required int32 term = 1;</code>
       */
      public Builder setTerm(int value) {
        bitField0_ |= 0x00000001;
        term_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 term = 1;</code>
       */
      public Builder clearTerm() {
        bitField0_ = (bitField0_ & ~0x00000001);
        term_ = 0;
        onChanged();
        return this;
      }

      private int candidateId_ ;
      /**
       * <code>required int32 candidateId = 2;</code>
       */
      public boolean hasCandidateId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 candidateId = 2;</code>
       */
      public int getCandidateId() {
        return candidateId_;
      }
      /**
       * <code>required int32 candidateId = 2;</code>
       */
      public Builder setCandidateId(int value) {
        bitField0_ |= 0x00000002;
        candidateId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 candidateId = 2;</code>
       */
      public Builder clearCandidateId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        candidateId_ = 0;
        onChanged();
        return this;
      }

      private int lastLogIndex_ ;
      /**
       * <code>required int32 lastLogIndex = 3;</code>
       */
      public boolean hasLastLogIndex() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int32 lastLogIndex = 3;</code>
       */
      public int getLastLogIndex() {
        return lastLogIndex_;
      }
      /**
       * <code>required int32 lastLogIndex = 3;</code>
       */
      public Builder setLastLogIndex(int value) {
        bitField0_ |= 0x00000004;
        lastLogIndex_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 lastLogIndex = 3;</code>
       */
      public Builder clearLastLogIndex() {
        bitField0_ = (bitField0_ & ~0x00000004);
        lastLogIndex_ = 0;
        onChanged();
        return this;
      }

      private int lastLogTerm_ ;
      /**
       * <code>required int32 lastLogTerm = 4;</code>
       */
      public boolean hasLastLogTerm() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required int32 lastLogTerm = 4;</code>
       */
      public int getLastLogTerm() {
        return lastLogTerm_;
      }
      /**
       * <code>required int32 lastLogTerm = 4;</code>
       */
      public Builder setLastLogTerm(int value) {
        bitField0_ |= 0x00000008;
        lastLogTerm_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 lastLogTerm = 4;</code>
       */
      public Builder clearLastLogTerm() {
        bitField0_ = (bitField0_ & ~0x00000008);
        lastLogTerm_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:LeaderElection)
    }

    static {
      defaultInstance = new LeaderElection(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:LeaderElection)
  }

  public interface LeaderElectionResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:LeaderElectionResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 from_node_id = 1;</code>
     */
    boolean hasFromNodeId();
    /**
     * <code>required int32 from_node_id = 1;</code>
     */
    int getFromNodeId();

    /**
     * <code>required int32 for_term = 2;</code>
     */
    boolean hasForTerm();
    /**
     * <code>required int32 for_term = 2;</code>
     */
    int getForTerm();

    /**
     * <code>required bool vote_granted = 3;</code>
     */
    boolean hasVoteGranted();
    /**
     * <code>required bool vote_granted = 3;</code>
     */
    boolean getVoteGranted();
  }
  /**
   * Protobuf type {@code LeaderElectionResponse}
   */
  public static final class LeaderElectionResponse extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:LeaderElectionResponse)
      LeaderElectionResponseOrBuilder {
    // Use LeaderElectionResponse.newBuilder() to construct.
    private LeaderElectionResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private LeaderElectionResponse(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final LeaderElectionResponse defaultInstance;
    public static LeaderElectionResponse getDefaultInstance() {
      return defaultInstance;
    }

    public LeaderElectionResponse getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private LeaderElectionResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              fromNodeId_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              forTerm_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              voteGranted_ = input.readBool();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Election.internal_static_LeaderElectionResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Election.internal_static_LeaderElectionResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              LeaderElectionResponse.class, Builder.class);
    }

    public static com.google.protobuf.Parser<LeaderElectionResponse> PARSER =
        new com.google.protobuf.AbstractParser<LeaderElectionResponse>() {
      public LeaderElectionResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new LeaderElectionResponse(input, extensionRegistry);
      }
    };

    @Override
    public com.google.protobuf.Parser<LeaderElectionResponse> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int FROM_NODE_ID_FIELD_NUMBER = 1;
    private int fromNodeId_;
    /**
     * <code>required int32 from_node_id = 1;</code>
     */
    public boolean hasFromNodeId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 from_node_id = 1;</code>
     */
    public int getFromNodeId() {
      return fromNodeId_;
    }

    public static final int FOR_TERM_FIELD_NUMBER = 2;
    private int forTerm_;
    /**
     * <code>required int32 for_term = 2;</code>
     */
    public boolean hasForTerm() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 for_term = 2;</code>
     */
    public int getForTerm() {
      return forTerm_;
    }

    public static final int VOTE_GRANTED_FIELD_NUMBER = 3;
    private boolean voteGranted_;
    /**
     * <code>required bool vote_granted = 3;</code>
     */
    public boolean hasVoteGranted() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required bool vote_granted = 3;</code>
     */
    public boolean getVoteGranted() {
      return voteGranted_;
    }

    private void initFields() {
      fromNodeId_ = 0;
      forTerm_ = 0;
      voteGranted_ = false;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasFromNodeId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasForTerm()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasVoteGranted()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, fromNodeId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, forTerm_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBool(3, voteGranted_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, fromNodeId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, forTerm_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(3, voteGranted_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static LeaderElectionResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static LeaderElectionResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static LeaderElectionResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static LeaderElectionResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static LeaderElectionResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static LeaderElectionResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static LeaderElectionResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static LeaderElectionResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static LeaderElectionResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static LeaderElectionResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(LeaderElectionResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code LeaderElectionResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:LeaderElectionResponse)
        LeaderElectionResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Election.internal_static_LeaderElectionResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Election.internal_static_LeaderElectionResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                LeaderElectionResponse.class, Builder.class);
      }

      // Construct using pipe.election.Election.LeaderElectionResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        fromNodeId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        forTerm_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        voteGranted_ = false;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Election.internal_static_LeaderElectionResponse_descriptor;
      }

      public LeaderElectionResponse getDefaultInstanceForType() {
        return LeaderElectionResponse.getDefaultInstance();
      }

      public LeaderElectionResponse build() {
        LeaderElectionResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public LeaderElectionResponse buildPartial() {
        LeaderElectionResponse result = new LeaderElectionResponse(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.fromNodeId_ = fromNodeId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.forTerm_ = forTerm_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.voteGranted_ = voteGranted_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof LeaderElectionResponse) {
          return mergeFrom((LeaderElectionResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(LeaderElectionResponse other) {
        if (other == LeaderElectionResponse.getDefaultInstance()) return this;
        if (other.hasFromNodeId()) {
          setFromNodeId(other.getFromNodeId());
        }
        if (other.hasForTerm()) {
          setForTerm(other.getForTerm());
        }
        if (other.hasVoteGranted()) {
          setVoteGranted(other.getVoteGranted());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasFromNodeId()) {
          
          return false;
        }
        if (!hasForTerm()) {
          
          return false;
        }
        if (!hasVoteGranted()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        LeaderElectionResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (LeaderElectionResponse) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int fromNodeId_ ;
      /**
       * <code>required int32 from_node_id = 1;</code>
       */
      public boolean hasFromNodeId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 from_node_id = 1;</code>
       */
      public int getFromNodeId() {
        return fromNodeId_;
      }
      /**
       * <code>required int32 from_node_id = 1;</code>
       */
      public Builder setFromNodeId(int value) {
        bitField0_ |= 0x00000001;
        fromNodeId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 from_node_id = 1;</code>
       */
      public Builder clearFromNodeId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        fromNodeId_ = 0;
        onChanged();
        return this;
      }

      private int forTerm_ ;
      /**
       * <code>required int32 for_term = 2;</code>
       */
      public boolean hasForTerm() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 for_term = 2;</code>
       */
      public int getForTerm() {
        return forTerm_;
      }
      /**
       * <code>required int32 for_term = 2;</code>
       */
      public Builder setForTerm(int value) {
        bitField0_ |= 0x00000002;
        forTerm_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 for_term = 2;</code>
       */
      public Builder clearForTerm() {
        bitField0_ = (bitField0_ & ~0x00000002);
        forTerm_ = 0;
        onChanged();
        return this;
      }

      private boolean voteGranted_ ;
      /**
       * <code>required bool vote_granted = 3;</code>
       */
      public boolean hasVoteGranted() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required bool vote_granted = 3;</code>
       */
      public boolean getVoteGranted() {
        return voteGranted_;
      }
      /**
       * <code>required bool vote_granted = 3;</code>
       */
      public Builder setVoteGranted(boolean value) {
        bitField0_ |= 0x00000004;
        voteGranted_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bool vote_granted = 3;</code>
       */
      public Builder clearVoteGranted() {
        bitField0_ = (bitField0_ & ~0x00000004);
        voteGranted_ = false;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:LeaderElectionResponse)
    }

    static {
      defaultInstance = new LeaderElectionResponse(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:LeaderElectionResponse)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_LeaderStatus_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_LeaderStatus_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_LeaderElection_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_LeaderElection_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_LeaderElectionResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_LeaderElectionResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\016election.proto\"\202\002\n\014LeaderStatus\022)\n\006act" +
      "ion\030\001 \002(\0162\031.LeaderStatus.LeaderQuery\022(\n\005" +
      "state\030\002 \001(\0162\031.LeaderStatus.LeaderState\022\023" +
      "\n\013leader_host\030\003 \001(\t\022\021\n\tleader_id\030\004 \001(\005\"A" +
      "\n\013LeaderState\022\021\n\rLEADERUNKNOWN\020\001\022\017\n\013LEAD" +
      "ERALIVE\020\002\022\016\n\nLEADERDEAD\020\003\"2\n\013LeaderQuery" +
      "\022\022\n\016WHOISTHELEADER\020\001\022\017\n\013THELEADERIS\020\002\"^\n" +
      "\016LeaderElection\022\014\n\004term\030\001 \002(\005\022\023\n\013candida" +
      "teId\030\002 \002(\005\022\024\n\014lastLogIndex\030\003 \002(\005\022\023\n\013last" +
      "LogTerm\030\004 \002(\005\"V\n\026LeaderElectionResponse\022",
      "\024\n\014from_node_id\030\001 \002(\005\022\020\n\010for_term\030\002 \002(\005\022" +
      "\024\n\014vote_granted\030\003 \002(\010B\021\n\rpipe.electionH\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_LeaderStatus_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_LeaderStatus_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_LeaderStatus_descriptor,
        new String[] { "Action", "State", "LeaderHost", "LeaderId", });
    internal_static_LeaderElection_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_LeaderElection_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_LeaderElection_descriptor,
        new String[] { "Term", "CandidateId", "LastLogIndex", "LastLogTerm", });
    internal_static_LeaderElectionResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_LeaderElectionResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_LeaderElectionResponse_descriptor,
        new String[] { "FromNodeId", "ForTerm", "VoteGranted", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
